// Package agency owns the realtor-facing catalog contract.
//
// HTTP, a future A2A adapter, and tests all call the same typed interface. The
// package does not know how a caller authenticated or where the catalog is
// stored; those details belong to adapters at its seams.
package agency

import (
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"math"
	"net/url"
	"strings"
)

// ErrPropertyNotFound deliberately covers both a missing property and a
// property owned by somebody else, so the catalog cannot be enumerated.
var ErrPropertyNotFound = errors.New("agency: property not found")

// ErrContactIntentConflict means one idempotency key was reused for a
// different listing.
var ErrContactIntentConflict = errors.New("agency: contact intent belongs to another property")

// ErrInvalidContactIntent means the caller did not supply the typed event
// contract expected by the catalog.
var ErrInvalidContactIntent = errors.New("agency: invalid contact intent")

// ErrInvalidProperty means editable catalog data is incomplete or malformed.
var ErrInvalidProperty = errors.New("agency: invalid property")

// ValidationError identifies the field that prevents a catalog mutation.
type ValidationError struct {
	Field  string
	Reason string
}

func (e ValidationError) Error() string {
	return fmt.Sprintf("%s: %s", e.Field, e.Reason)
}

func (e ValidationError) Unwrap() error { return ErrInvalidProperty }

// Owner is the authenticated catalog owner as the application layer sees it.
// ID is opaque so a managed identity provider can replace local accounts.
type Owner struct {
	ID   string
	Name string
}

// Money keeps an unpublished amount distinct from a published zero.
type Money struct {
	Amount   *float64 `json:"amount,omitempty"`
	Currency string   `json:"currency,omitempty"`
}

// PropertyInput is the editable, deterministic part of a catalog entry.
// Prose-derived attributes stay in the parsing pipeline and are not accepted
// from this management interface.
type PropertyInput struct {
	URL           string   `json:"url"`
	Neighborhood  string   `json:"neighborhood"`
	Address       string   `json:"address,omitempty"`
	Description   string   `json:"description"`
	Operation     string   `json:"operation"`
	Price         Money    `json:"price"`
	Expenses      Money    `json:"expenses"`
	TotalAreaM2   *float64 `json:"total_area_m2,omitempty"`
	CoveredAreaM2 *float64 `json:"covered_area_m2,omitempty"`
	Rooms         *int     `json:"rooms,omitempty"`
	Bedrooms      *int     `json:"bedrooms,omitempty"`
	Bathrooms     *int     `json:"bathrooms,omitempty"`
	ParkingSpaces *int     `json:"parking_spaces,omitempty"`
	AgeYears      *int     `json:"age_years,omitempty"`
	Floor         string   `json:"floor,omitempty"`
}

// Property is one active entry in an agency catalog.
type Property struct {
	ID           string `json:"id"`
	Agency       string `json:"agency"`
	Source       string `json:"source"`
	ContactCount int    `json:"contact_count"`
	PropertyInput
}

// ContactSource identifies the product surface that recorded an intent.
type ContactSource string

const (
	// ContactSourceSearchResultCard is the buyer-facing property card CTA.
	ContactSourceSearchResultCard ContactSource = "search_result_card"
)

// ContactIntent is generated by the caller once per deliberate activation.
// ID is an idempotency key; callers never send an aggregate count.
type ContactIntent struct {
	ID     string        `json:"intent_id"`
	Source ContactSource `json:"source"`
}

// ContactReceipt confirms that the intent is represented in the aggregate.
// Created is transport metadata used to choose 201 versus an idempotent 200.
type ContactReceipt struct {
	IntentID  string `json:"intent_id"`
	ListingID string `json:"listing_id"`
	Recorded  bool   `json:"recorded"`
	Created   bool   `json:"-"`
}

// Catalog is the application seam for realtor inventory. Callers provide an
// authenticated owner ID; adapters are responsible for durable storage.
type Catalog interface {
	List(ctx context.Context, ownerID string) ([]Property, error)
	Add(ctx context.Context, owner Owner, input PropertyInput) (Property, error)
	Update(ctx context.Context, ownerID, propertyID string, input PropertyInput) (Property, error)
	Remove(ctx context.Context, ownerID, propertyID string) error
	RecordContactIntent(ctx context.Context, propertyID string, intent ContactIntent) (ContactReceipt, error)
}

// PreparePropertyInput normalizes and validates editable facts before an
// adapter stores them.
func PreparePropertyInput(input PropertyInput) (PropertyInput, error) {
	input.URL = strings.TrimSpace(input.URL)
	input.Neighborhood = strings.ToLower(strings.TrimSpace(input.Neighborhood))
	input.Address = strings.TrimSpace(input.Address)
	input.Description = strings.TrimSpace(input.Description)
	input.Operation = strings.ToLower(strings.TrimSpace(input.Operation))
	input.Price.Currency = strings.ToUpper(strings.TrimSpace(input.Price.Currency))
	input.Expenses.Currency = strings.ToUpper(strings.TrimSpace(input.Expenses.Currency))
	input.Floor = strings.TrimSpace(input.Floor)

	parsedURL, err := url.ParseRequestURI(input.URL)
	if err != nil || (parsedURL.Scheme != "http" && parsedURL.Scheme != "https") || parsedURL.Host == "" {
		return PropertyInput{}, ValidationError{Field: "url", Reason: "debe ser una URL http o https"}
	}
	if input.Neighborhood == "" {
		return PropertyInput{}, ValidationError{Field: "neighborhood", Reason: "es obligatorio"}
	}
	if input.Description == "" {
		return PropertyInput{}, ValidationError{Field: "description", Reason: "es obligatoria"}
	}
	if input.Operation != "alquiler" && input.Operation != "alquiler_temporal" && input.Operation != "venta" {
		return PropertyInput{}, ValidationError{Field: "operation", Reason: "no es válida"}
	}
	if err := validateMoney("price", input.Price); err != nil {
		return PropertyInput{}, err
	}
	if err := validateMoney("expenses", input.Expenses); err != nil {
		return PropertyInput{}, err
	}
	for _, field := range []struct {
		name  string
		value *float64
	}{
		{name: "total_area_m2", value: input.TotalAreaM2},
		{name: "covered_area_m2", value: input.CoveredAreaM2},
	} {
		if field.value != nil && (*field.value < 0 || math.IsNaN(*field.value) || math.IsInf(*field.value, 0)) {
			return PropertyInput{}, ValidationError{Field: field.name, Reason: "no puede ser negativo ni infinito"}
		}
	}
	for _, field := range []struct {
		name  string
		value *int
	}{
		{name: "rooms", value: input.Rooms},
		{name: "bedrooms", value: input.Bedrooms},
		{name: "bathrooms", value: input.Bathrooms},
		{name: "parking_spaces", value: input.ParkingSpaces},
		{name: "age_years", value: input.AgeYears},
	} {
		if field.value != nil && *field.value < 0 {
			return PropertyInput{}, ValidationError{Field: field.name, Reason: "no puede ser negativo"}
		}
	}
	return input, nil
}

func validateMoney(field string, money Money) error {
	if money.Amount != nil && (*money.Amount < 0 || math.IsNaN(*money.Amount) || math.IsInf(*money.Amount, 0)) {
		return ValidationError{Field: field + ".amount", Reason: "no puede ser negativo ni infinito"}
	}
	if money.Currency != "" && money.Currency != "ARS" && money.Currency != "USD" {
		return ValidationError{Field: field + ".currency", Reason: "debe ser ARS o USD"}
	}
	if money.Amount != nil && money.Currency == "" {
		return ValidationError{Field: field + ".currency", Reason: "es obligatoria cuando hay un monto"}
	}
	return nil
}

// ValidateContactIntent checks the cross-transport event contract.
func ValidateContactIntent(intent ContactIntent) error {
	if intent.Source != ContactSourceSearchResultCard {
		return ErrInvalidContactIntent
	}
	parts := strings.Split(intent.ID, "-")
	if len(parts) != 5 || len(parts[0]) != 8 || len(parts[1]) != 4 || len(parts[2]) != 4 || len(parts[3]) != 4 || len(parts[4]) != 12 {
		return ErrInvalidContactIntent
	}
	for _, part := range parts {
		if _, err := hex.DecodeString(part); err != nil {
			return ErrInvalidContactIntent
		}
	}
	return nil
}
